Reaction field for category and stori
SpaceyaTech/mastori-backend pull request #36
Opened 2023-03-03 12:17 UTC by aibunny

Fixes #30

2023-03-07 11:16 UTC, JimmyTron reviewed
Have to go thru still will give feedback

2023-03-07 11:23 UTC, JimmyTron commented
check on the conflicts.
![image](https://user-images.githubusercontent.com/23496280/223408333-c29ea2c2-f82f-4b91-a7e5-226d5aeb786c.png)

2023-03-10 05:48 UTC, hellen-22 approved these changes

2023-03-10 15:27 UTC, JimmyTron submitted a review, later dismissed

2023-03-18 05:55 UTC, JimmyTron requested changes
missing the storage moule
`pip install django-storages`
add to the requirements file

2023-04-27 14:41 UTC, closed without merging