S3bucket
SpaceyaTech/mastori-backend pull request #43
Opened 2023-03-07 14:18 UTC by aibunny

# Description
I added the s3 bucket for persistent images but i left out the access and secret keys part keys part for later when we have an amazon account for the project.

2023-03-10 01:15 UTC, JimmyTron reviewed
**Expected Changes**

1. Requirments:  `Install boto3 and django-storages packages using pip.`
2. configuration to your project's urls.py file to serve static and media files from S3: 
![Screenshot from 2023-03-10 04-02-19](https://user-images.githubusercontent.com/23496280/224197013-5bccc1e5-d0f0-4efb-b457-82c5bce0183b.png)

## The changes are spanning beyond the scope of the pull request which is not a good thing. Try to only implement a single feature per pull request. It make reviews easier and reduces chances of introducing bugs.

> For instance on this we have tree unrelated fixes:

1. `Reactions`
2. `S3 storage`
3. `Readme Update`

2023-03-10 08:30 UTC, aibunny commented on CMS/settings.py
> +AWS_QUERYSTRING_AUTH = False
the settings in my pr are for a public bucket the other settings are made during the creating of the bucket in the s3 console as part of the bucket policy. Remember we're using this bucket for images which are supposed to be publicly uploaded and read by anyone using the cms, so we don't actually need ``` AWS_DEFAULT_ACL = None```. But if we want to upload our static files to s3 bucket the we can make the bucket private or the particular folder for images and videos  can be set to public read

2023-03-10 08:37 UTC, aibunny commented on blog/models.py
> +        return True
It doesn't appear as changed its part of the comments

2023-03-10 10:38 UTC, JimmyTron commented on blog/models.py
> +    parent_comment = models.ForeignKey('self',on_delete=models.CASCADE,blank=True,null=True,related_name='replies')
Im yet to confirm this though

2023-03-14 18:39 UTC, JimmyTron approved these changes

2023-03-18 06:36 UTC, JimmyTron requested changes
Requirements missing 
> check also pull request #36

2023-04-09 17:11 UTC, JimmyTron submitted a review, later dismissed

2023-04-13 04:53 UTC, Rioba-Ian approved these changes

2023-06-17 03:57 UTC, closed without merging