Account Management
SpaceyaTech/mastori-backend pull request #61
Opened 2023-03-21 09:14 UTC by hellen-22

# Description

Allow viewing, updating and deleting of user accounts

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

[![CI Django & Postgres Tests](https://github.com/SpaceyaTech/blog/actions/workflows/django-postgres-ci.yml/badge.svg)](https://github.com/SpaceyaTech/blog/actions/workflows/django-postgres-ci.yml)

[![Jambo](https://github.com/SpaceyaTech/mastori/actions/workflows/jambo.yaml/badge.svg)](https://github.com/SpaceyaTech/mastori/actions/workflows/jambo.yaml)

**Test Configuration**:

```sql
          python manage.py migrate
          python manage.py test
```

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-03-21 13:35 UTC, aibunny submitted a review, later dismissed

2023-03-21 14:26 UTC, JimmyTron submitted a review, later dismissed

2023-03-21 16:40 UTC, Saint-Chris-7 submitted a review, later dismissed

2023-03-30 00:39 UTC, JimmyTron requested changes
Check on the auth of the endpoints

2023-03-30 00:39 UTC, JimmyTron commented on accounts/views.py
> +    #permission_classes = [IsAuthenticated]
Looks like you forgot to uncomment the permision class.
I could view accounts even without loging in
![Screenshot from 2023-03-30 03-28-46](https://user-images.githubusercontent.com/23496280/228698006-2a21a519-e3a9-4133-ab8b-16a583146e9d.png)

2023-03-30 00:39 UTC, JimmyTron commented on accounts/serializers.py
Is it feasible to probably have less serializer or having several. I see some serializers having simmilar data. is it possible to refactor

2023-04-01 00:23 UTC, JimmyTron approved these changes

2023-04-03 07:01 UTC, hellen-22 commented on accounts/serializers.py
Yes, I'll refactor

2023-04-03 12:04 UTC, Saint-Chris-7 approved these changes

2023-04-03 23:25 UTC, JimmyTron commented on accounts/views.py
> +    #permission_classes = [IsAuthenticated]
ok

2023-04-09 17:10 UTC, JimmyTron approved these changes

2023-05-01 11:57 UTC, Saint-Chris-7 approved these changes

2023-06-17 09:54 UTC, aibunny approved these changes

2023-08-07 06:52 UTC, closed without merging